version: 2
jobs:
#  shellcheck:
#    docker:
#      - image: nlknguyen/alpine-shellcheck:v0.4.6
#    steps:
#      - checkout
#      - run:
#          name: ShellCheck all scripts
#          command: |
#            find . -type f -name '*.sh' | wc -l
#            find . -type f -name '*.sh' | xargs shellcheck --external-sources
  build:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v2-{{ .Branch }}-{{ .Revision }}
            - v2-{{ .Branch }}-
            - v2-
          paths:
            - /caches/app.tar
      - run:
          name: Load docker image layer cache
          command: |
            docker load -i /caches/app.tar 2>&1 || true
      - run:
          name: Login to Dockerhub
          command: |
            set -u
            docker login --username "${DOCKER_USER:-$CIRCLE_USERNAME}" --password "${DOCKER_PASS}"
      - run:
          name: Fetch or build docker image
          command: |
            # If the reponame starts with "docker-", strip that off.
            # First check to see if the image has already been built,
            # because Build Binaries Only Once.
            PROJECT_LC=$(echo "${CIRCLE_PROJECT_USERNAME}" | tr '[:upper:]' '[:lower:]')
            docker pull "${PROJECT_LC}/${CIRCLE_PROJECT_REPONAME#docker-}:${CIRCLE_SHA1}" \
            || docker build --cache-from=app -t "${PROJECT_LC}/${CIRCLE_PROJECT_REPONAME#docker-}:${CIRCLE_SHA1}" --label circle.sha="${CIRCLE_SHA1}" --label circle.build_num="${CIRCLE_BUILD_NUM}" .
      - run:
          name: Save docker image layer cache
          command: |
            mkdir -p /caches
            PROJECT_LC=$(echo "${CIRCLE_PROJECT_USERNAME}" | tr '[:upper:]' '[:lower:]')
            docker save -o /caches/app.tar "${PROJECT_LC}/${CIRCLE_PROJECT_REPONAME#docker-}:${CIRCLE_SHA1}" $(docker history -q "${PROJECT_LC}/${CIRCLE_PROJECT_REPONAME#docker-}:${CIRCLE_SHA1}" | grep -v missing)
      - save_cache:
          key: v2-{{ .Branch }}-{{ .Revision }}
          paths:
            - /caches/app.tar

      - run:
          name: Run tests WRITEME!!!
          command: |
            #docker-compose -f ./docker-compose.test.yml up
            true

      - run:
          name: Tag and push to Dockerhub
          command: |
            PROJECT_LC=$(echo "${CIRCLE_PROJECT_USERNAME}" | tr '[:upper:]' '[:lower:]')
            if [ "${CIRCLE_BRANCH}" ]; then
              docker tag "${PROJECT_LC}/${CIRCLE_PROJECT_REPONAME#docker-}:${CIRCLE_SHA1}" "${PROJECT_LC}/${CIRCLE_PROJECT_REPONAME#docker-}:${CIRCLE_BRANCH}"
              # git master == docker latest
              test "master" == "${CIRCLE_BRANCH}" \
              && docker tag "${PROJECT_LC}/${CIRCLE_PROJECT_REPONAME#docker-}:${CIRCLE_SHA1}" "${PROJECT_LC}/${CIRCLE_PROJECT_REPONAME#docker-}:latest"
            elif [ "${CIRCLE_TAG}" ]; then
              docker tag "${PROJECT_LC}/${CIRCLE_PROJECT_REPONAME#docker-}:${CIRCLE_SHA1}" "${PROJECT_LC}/${CIRCLE_PROJECT_REPONAME#docker-}:${CIRCLE_TAG}"
            fi
            docker push "${PROJECT_LC}/${CIRCLE_PROJECT_REPONAME#docker-}"

workflows:
  version: 2
  workflow:
    jobs:
#      - shellcheck:
#          filters:
#            tags:
#              only: /.*/
      - build:
          context: github_public_repo
#          requires:
#            - build
          filters:
            tags:
              only: /.*/
